### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [pRizz/iota.transactionSpammer.js#11]
Hi pRizz,

I was wondering if I can run the spammer from the commandline, and if that is possible could you provide instruction for how to do that?

Thanks!

**Comment by pRizz** [comment]
Hi @lekanovic, yes it can! But the restriction right now is that it only works on Mac right now; there are issues on Windows and Unix based distros I've seen.

Here is the repo for that. https://github.com/pRizz/iota-transaction-spammer-cli#readme

Eventually, I'll update this repo as well to be more flexible.

**Comment by ghost** [comment]
Perfect that is exactly what I needed, thanks
